env:
  es2020: true
  browser: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  sourceType: module
rules:
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - error
    - ignoreRestSiblings: true
      argsIgnorePattern: ^_
  prefer-arrow-callback: error
