name: Dependabot Auto Merge

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  auto_merge:
    runs-on: macos-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.WRITABLE_TOKEN }}
          script: |
            const output = `@dependabot squash and merge`;
            github.issues.createComment({
              issue_number: ${{ github.event.workflow_run.pull_requests[0].number }},
              owner: "${{ github.event.repository.owner.login }}",
              repo: "${{ github.event.repository.name }}",
              body: output
            })
